[package]
name = "foveacore"
version = "0.2.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", tag = "v0.2.1" }

[workspace]
members = ["splat_sorter"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
