[package]
name = "fovea_splat_sorter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", tag = "v0.2.1" }
glam = { version = "0.29", features = ["bytemuck"] }
bytemuck = { version = "1.21", features = ["derive"] }
rayon = "1.10"

[features]
default = []
multithread = []
